
Please note that in the future you will need to specify an explicit version
also when loading the 'anaconda' module, just as is already required for the
compiler and MPI modules. In case you need to load the anaconda module for your
jobs, please adapt your submit scripts already now. Use

  module load anaconda/3/2021.11

to load version 3/2021.11 explicitly, for example.


Loading pytorch/gpu-cuda-11.2/1.8.0
  Loading requirement: cuda/11.2

Loading h5py-mpi/2.10
  Loading requirement: mpi4py/3.0.3
WARNING: You are using pip version 19.2.3, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
WARNING: You are using pip version 19.2.3, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
02/08/2024 14:07:28 - INFO - root -   Using a single GPU for training.
02/08/2024 14:07:28 - INFO - trphysx.embedding.embedding_lorenz -   Number of embedding parameters: 36192
02/08/2024 14:07:28 - INFO - trphysx.embedding.embedding_model -   Loading embedding model from file: ./embedding_lorenz300.pth
02/08/2024 14:08:05 - INFO - trphysx.transformer.phys_transformer_gpt2 -   Number of parameters: 53984
02/08/2024 14:08:05 - INFO - trphysx.transformer.phys_transformer_base -   Loading embedding model from file: ./transformer_lorenz200.pth
Traceback (most recent call last):
  File "examples/lorenz/predict_lorenz.py", line 63, in <module>
    cache_path='./cache')
  File "/raven/u/sashb/projects/github_repos/transformer-physx/trphysx/data_utils/dataset_phys.py", line 53, in __init__
    assert os.path.isfile(file_path), 'Provided data file path does not exist!'
AssertionError: Provided data file path does not exist!
srun: error: ravg1079: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=9303598.0
